# Generated by Django 5.1.2 on 2025-03-29 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_image', models.URLField()),
                ('evolution1_image', models.URLField()),
                ('evolution2_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hunger', models.IntegerField(default=60)),
                ('energy', models.IntegerField(default=60)),
                ('happiness', models.IntegerField(default=60)),
                ('current_image', models.URLField()),
                ('evolution_stage', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.petbase')),
            ],
        ),
    ]
